### ISSUE TITLE
Trailing slash required

### ISSUE THREAD

**Issue by saltzmanjoelh** [adam-fowler/aws-signer#5]
Hi,

It's not an issue just maybe something to note in the README in the signHeaders example. If you don't include the trailing slash in the URL, you will get an InvalidSignatureException from AWS. Adding the trailing slash fixes the issue. This was with using POST for DynamoDB. 

For anyone curious:

Here is my URL without the trailing slashes

**po signingData.unsignedURL**
`https://dynamodb.us-west-1.amazonaws.com`

**po signingData.unsignedURL.path**
`""`

As per step 2 in Task 1 of [Signing AWS Requests](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html)

> Add the canonical URI parameter ...
 
> Example Canonical URI with encoding
> `/documents%2520and%2520settings/`

> Example Canonical URI
> `/`

So, no trailing slash == 400

**Comment by adam-fowler** [comment]
Probably can fix that in code

**Comment by saltzmanjoelh** [comment]
Do you want me to take a crack at it? Do you have any preferences on where or how I handle it?

**Comment by adam-fowler** [comment]
@saltzmanjoelh if you want to take a crack I'd be very happy for you to do it. I guess you need to fixup the url at the top of signURL() and signHeaders(). Or perhaps you could fixup the URL in `SigningData.Init`.

**Comment by adam-fowler** [comment]
Release https://github.com/adam-fowler/aws-signer-v4/releases/tag/2.1.1
